spring:
  datasource:
    url: jdbc:mysql://47.104.26.79:3306/atits?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 46132205092017
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

